spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer-service

#  spring:
#    config:
#      import: optional:configserver:http://localhost:8888
#  This tells Spring Boot to import configuration properties from an external Spring Cloud Config Server.
#  http://localhost:8888 is the URL of your Config Server.
#  optional: means: If the Config Server is not available, don’t fail — just keep running with local config.